<?php

namespace ierusalim\Random;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-07 at 21:57:01.
 */
class RandomStrTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RandomStr
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new RandomStr();
    }

    /**
     * @covers ierusalim\Random\RandomStr::genRandomStr
     * @todo   Implement testGenRandomStr().
     */
    public function testGenRandomStr()
    {
        for ($len = 0; $len < 10; $len++) {
            $bytes = $this->object->genRandomStr($len);
            if ($len) {
                $this->assertTrue(is_string($bytes));
                $this->assertEquals(strlen($bytes), $len);
            } else {
                $this->assertFalse($bytes);
            }
        }
        for ($len = 100; $len < 100000; $len += (int) ($len / 7)) {
            $bytes = $this->object->genRandomStr($len);
            $this->assertTrue(strlen($bytes) == $len);
        }
        $prev = '';
        $len = 7;
        for ($i = 0; $i < 100; $i++) {
            $bytes = $this->object->genRandomStr($len);
            $this->assertFalse($bytes === $prev);
            $prev = $bytes;
        }
    }

    /**
     * @covers ierusalim\Random\RandomStr::genRandomBytes
     * @todo   Implement testGenRandomBytes().
     */
    public function testGenRandomBytes()
    {
        for ($len = 0; $len < 100000; $len += (int) ($len / 10) + 1) {
            $bytes = $this->object->genRandomBytes($len);
            if ($len) {
                $this->assertTrue(is_string($bytes));
                $this->assertTrue(strlen($bytes) == $len);
            } else {
                $this->assertFalse($bytes);
            }
        }
    }

    /**
     * @covers ierusalim\Random\RandomStr::md5RandomBytes
     * @todo   Implement testMd5RandomBytes().
     */
    public function testMd5RandomBytes()
    {
        for ($len = 0; $len < 100000; $len += $len + 1) {
            $bytes = $this->object->md5RandomBytes($len);
            if ($len) {
                $this->assertTrue(is_string($bytes));
                $this->assertTrue(strlen($bytes) == $len);
            } else {
                $this->assertTrue(!is_string($bytes));
                $this->assertFalse($bytes);
            }
        }
    }
    
    public function testSetChars() {
        $gen_chars = "神會貓性少女 迪克和陰部";
        $gen_chars_len = mb_strlen($gen_chars, 'UTF-8');
        $gen_chars_arr = preg_split('//u', $gen_chars, null, PREG_SPLIT_NO_EMPTY);
        $this->assertEquals($gen_chars_len, count($gen_chars_arr));

        $this->object->setChars($gen_chars, true);
        $gen_str_len = 100;
        $gen_str = $this->object->genRandomStr($gen_str_len);
        $real_gen_str_len = mb_strlen($gen_str, 'UTF-8');
        $this->assertEquals($gen_str_len, $real_gen_str_len);

        $gen_str_arr = preg_split('//u', $gen_str, null, PREG_SPLIT_NO_EMPTY);
        $this->assertEquals($gen_str_len, count($gen_str_arr));
        
        $errs=0;
        foreach($gen_str_arr as $mb_ch) {
            if(!in_array($mb_ch, $gen_chars_arr)) $errs++;
        }
        $this->assertTrue(!$errs);
    }
}
